  
name: Docker Image CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Build
        run: docker build -t chrisns/vdi:latest .

      - name: Docker login
        if: github.ref == 'refs/heads/master'
        env:
          docker_username: ${{ secrets.docker_username }}
          docker_password: ${{ secrets.docker_password }}
        run: docker login  -u $docker_username -p ${docker_password}

      - name: Tag
        run: docker tag chrisns/vdi:latest chrisns/vdi:${GITHUB_SHA}

      - name: Push latest
        if: github.ref == 'refs/heads/master'
        run: docker push chrisns/vdi:latest

      - name: Push sha
        run: docker push chrisns/vdi:${GITHUB_SHA}
